### GET all contacts
GET http://localhost:3000/contacts
Content-Type: application/json


### GET contact by ID
GET http://localhost:3000/contacts/69055f50808316e9f4da46db
Content-Type: application/json

### CREATE a new contact (POST)
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Sarah",
  "lastName": "Birch",
  "email": "test@gmail.com",
  "favoriteColor": "Green",
  "birthday": "1998-05-20"
}


### UPDATE a contact (PUT)
PUT http://localhost:3000/contacts/690ec02499a8afe80d2dddf6 HTTP/1.1
Content-Type: application/json

{
  "_id": "69055f50808316e9f4da46db",
  "firstName": "Julia",
  "lastName": "Smith",
  "email": "test@example.com",
  "favoriteColor": "Blue",
  "birthday": "1998-08-15"
}


### DELETE a contact
DELETE http://localhost:3000/contacts/690ec06499a8afe80d2dddf7
Content-Type: application/json


